export const SET_COURSES = 'SET_COURSES'
export const SET_COURSE = 'SET_COURSE'
export const ADD_COURSE = 'ADD_COURSE'

export const ADD_COURSE_LINE = 'ADD_COURSE_LINE'
export const REMOVE_COURSE_LINE = 'REMOVE_COURSE_LINE'
export const UPDATE_COURSE_LINE = 'UPDATE_COURSE_LINE'
export const UPDATE_COURSE_VALUE = 'UPDATE_COURSE_VALUE'

export const SET_CATEGORIES = 'SET_CATEGORIES'

export const SET_USER = 'SET_USER'

export const SET_LOADING = 'SET_LOADING'
export const SET_ERROR = 'SET_ERROR'
